# Generated by Django 5.1.6 on 2025-02-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Student_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_name', models.CharField(max_length=220)),
                ('Student_department', models.CharField(max_length=220)),
                ('Student_city', models.CharField(max_length=220)),
                ('Student_age', models.IntegerField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=220)),
                ('book_author', models.CharField(max_length=220)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='lms_app.category')),
            ],
        ),
    ]
