# Generated by Django 5.1.6 on 2025-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_rename_book_name_book_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='Student_age',
            field=models.IntegerField(),
        ),
    ]
