# Generated by Django 5.1.6 on 2025-02-25 13:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_rename_name_author_author_name_alter_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrow_date', models.DateField(default=datetime.date(2025, 3, 11))),
                ('returned_date', models.BooleanField(default=False)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_FullName', models.CharField(max_length=220)),
                ('Member_Email', models.CharField(max_length=220)),
                ('Member_department', models.CharField(max_length=220)),
                ('Member_city', models.CharField(max_length=220)),
                ('Member_age', models.IntegerField()),
                ('membership_type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], max_length=100)),
                ('expeiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversed_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Book',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='000-0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.book'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.member'),
        ),
    ]
