# Generated by Django 5.1.6 on 2025-02-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_barrow_member_reservation_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Member_Email',
            new_name='member_Email',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Member_FullName',
            new_name='member_FullName',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Member_age',
            new_name='member_age',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Member_city',
            new_name='member_city',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Member_department',
            new_name='member_department',
        ),
    ]
