# Generated by Django 5.1.6 on 2025-02-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_rename_member_email_member_member_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_FullName',
            new_name='member_full_name',
        ),
    ]
