# Generated by Django 5.1.6 on 2025-02-26 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_rename_member_fullname_member_member_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='expeiry_date',
            new_name='expiry_date',
        ),
        migrations.AlterField(
            model_name='barrow',
            name='barrow_date',
            field=models.DateField(default=datetime.date(2025, 3, 12)),
        ),
    ]
