# Generated by Django 5.1.6 on 2025-02-27 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_remove_category_category_name_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, to='lms_app.book'),
        ),
        migrations.AlterField(
            model_name='barrow',
            name='barrow_date',
            field=models.DateField(default=datetime.date(2025, 3, 13)),
        ),
    ]
