# Generated by Django 5.1.6 on 2025-02-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_member_borrowed_books_alter_barrow_barrow_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='expiry_date',
            new_name='expeiry_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_full_name',
            new_name='member_Full_Name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Member',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='borrowed_books',
        ),
    ]
