# Generated by Django 5.1.6 on 2025-02-28 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0014_rename_expeiry_date_member_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(default=datetime.date(2025, 3, 14))),
                ('returned_date', models.BooleanField(default=False)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Barrow',
        ),
    ]
